schema_version = "1.0.0"
id = "camera_grid"
version = "1.6.1"
name = "Camera Grid"
tagline = "Browse and switch cameras from a grid overlay in the viewport"
maintainer = "Nadir Perazzo"
website = "https://github.com/n4dirp/CamGrid"
type = "add-on"
tags = ["Camera", "User Interface"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
